version: '3.1'
services:
  mongodb:
    image: mongo:4.0
    user: "root"
    restart: always
    command: mongod --storageEngine mmapv1
    # command: tail -f /dev/null
    volumes:
      # [local directory]:[container directory]
      - ../../db/mongodb:/data
      # [local file]:[container file]
      - "./mongodb/mongod.conf:/etc/mongod.conf"
    ports:
      - 27027:27017
    networks:
      - backend
  # bring these back when sk has configured an express image
  # nginx-proxy:
  #   image: nginx:stable
  #   user: "root"
  #   restart: always
  #   volumes:
  #     - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  #     - ../../www-static/:/www-static
  #   ports:
  #     - 80:80
  #   networks:
  #     - backend
  #   depends_on:
  #     - express-content
  #     - express-feedback
  express-content:
    tty: true # Enables debugging capabilities when attached to this container.
    image: base-express
    user: "root"
    restart: "always"
    command:  /bin/sh -c "yarn --cwd api build && node api/dist/bootstrap.js"

    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/content
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongodb
    ports:
      - 3000:3000
      - 5102:5101
    volumes:
      - ../../app/content:/root/app
      - ../../api/content_api:/root/api
    networks:
      - backend
  # express-feedback:
  #   tty: true # Enables debugging capabilities when attached to this container.
  #   image: 'bitnami/express:4'
  #   user: "root"
  #   restart: always
  #   command: npm start
  #   environment:
  #     - PORT=3001
  #     - NODE_ENV=development
  #     - DATABASE_URL=mongodb://mongodb:27017/content
  #     - SKIP_DB_WAIT=0
  #     - SKIP_DB_MIGRATION=0
  #     - SKIP_NPM_INSTALL=0
  #     - SKIP_BOWER_INSTALL=0
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ../../app/feedback:/app
  #   networks:
  #     - backend
networks:
  backend:

